config/routes.rb
Rails.application.routes.draw do
  root           'static_pages#home'
  get 'help'  => 'static_pages#help'
  get 'about' => 'static_pages#about'
  resources :admins, only: [:index, :update, :destroy]
  resources :articles
  resources :contacts

  # See https://goo.gl/xamqba, to avoid the route conflicts.
  devise_for :admins, path: 'devise'

  get 'material_orders'    => 'material_orders#index'
  get 'new_material_order' => 'material_orders#new'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  enum role: [:nobody, :guest, :operator, :expert, :vip, :root]
  
  after_initialize :set_default_role, :if => :new_record?

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  private
  
  def set_default_role
    self.role ||= :nobody
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  enum role:     [:supplier, :client, :shipper, :all_above, :other]
  enum priority: [:vip, :important, :ordinary, :bad, :worse, :worst]
  
  before_save { self.email = email.downcase }

  validates :name, presence: true,
                   uniqueness: { case_sensitive: false },
                   length: { maximum: 60 }
  validates :mobile, allow_nil: true,
                     allow_blank: true,
                     length: { maximum: 20 }
  validates :phone, allow_nil: true,
                    allow_blank: true,
                    length: { maximum: 30 }
  validates :address, allow_nil: true,
                      allow_blank: true,
                      length: { maximum: 255 }
  validates :email, allow_nil: true,
                    allow_blank: true,
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    case_sensitive: false
end

app/models/material_order.rb
class MaterialOrder < ActiveRecord::Base
  belongs_to :contact
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :set_admin, only: [:update, :destroy]

  def index
    @admins = Admin.all
  end

  # def show
  # end

  # PATCH/PUT /admins/1
  # PATCH/PUT /admins/1.json
  def update
    respond_to do |format|
      if @admin.update_attributes(admin_params)
        format.html { redirect_to admins_url }
        flash[:success] = 'Admin was successfully updated!'
        format.json { render :show, status: :ok, location: @admin }
      else
        format.html { render :edit }
        format.json { render json: @admin.errors,
                             status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/1
  # DELETE /admins/1.json
  def destroy
    @admin.destroy
    respond_to do |format|
      format.html { redirect_to admins_url }
      flash[:success] = 'Admin was successfully destroyed!'
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_admin
    @admin = Admin.find(params[:id])
  end

  def admin_params
    params.require(:admin).permit(:name, :role, :email)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Selects a locale.
  before_action :set_locale

  protected

  def set_locale
    #lang = 'en'
    lang = 'zh_CN'
    I18n.locale = lang
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to articles_path,
                                  notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors,
                             status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article,
                                  notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors,
                             status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url,
                                notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_article
    @article = Article.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list
  # through.
  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.paginate(page: params[:page])
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|    
      if @contact.save
        format.html { redirect_to contacts_path }
        flash[:success] = 'Contact was successfully created!'
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors,
                             status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update_attributes(contact_params)
        format.html { redirect_to @contact }
        flash[:success] = 'Contact was successfully updated!'
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors,
                             status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url }
      flash[:success] = 'Contact was successfully destroyed!'
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_contact
    @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:name, :mobile, :phone,:role, :priority,
                                    :address, :email, :note)
  end
end

app/controllers/material_orders_controller.rb
class MaterialOrdersController < ApplicationController
  def index
  end

  def new
  	@material_order = MaterialOrder.new
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def xeditable? object = nil
    true # Or something like current_user.xeditable?
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
  def find_all_suppliers()
  	Contact.where(role: "supplier")
  	# Contact.where(role: 0) # OK
  	# Contact.where(role: :supplier) # returns empty []
  end
end

app/helpers/material_orders_helper.rb
module MaterialOrdersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admins/_row.html.erb
<% admin = row %>

<td><%= editable admin, :name %></td>
<td><%= editable admin, :role, type: :select, data: { source: roles } %></td>
<td><%= editable admin, :email %></td>
<td><%= admin.sign_in_count %></td>
<td><%= admin.current_sign_in_at %></td>
<td><%= admin.last_sign_in_at %></td>
<td><%= admin.current_sign_in_ip %></td>
<td><%= admin.last_sign_in_ip %></td>
<td><%= admin.created_at %></td>
<td><%= admin.updated_at %></td>
<!--
<td><%#= link_to 'Show', admin, class: 'btn btn-primary btn-xs' %></td>
-->
<td>
  <%= link_to admin_path(admin),
              method: :delete,
              data: { confirm: 'You sure?' },
              class: 'btn btn-danger btn-xs' do %>
    <i class="glyphicon glyphicon-remove"></i> Destroy
  <% end %>     
</td>

app/views/admins/index.html.erb
<% provide(:title, "All Admins") %>

<h3 style="margin: 30px 0px">Listing Admins</h3>
<% count = 0 %>
<% roles = Admin.roles.keys.to_a %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>No.</th>
      <th>Name</th>
      <th>Role</th>
      <th>Email</th>
      <th>Sign-in Count</th>
      <th>Current Sign-in At</th>
      <th>Last Sign-in At</th>
      <th>Current Sign-in IP</th>
      <th>Last Sign-in IP</th>
      <th>Created At</th>
      <th>Updated At</th>      
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% @admins.each do |admin| %>
      <% count += 1 %>
      <tr>
        <td><%= count %></td>
        <%= render partial: 'row',
                   object: admin,
                   locals: { roles: roles } %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Home', root_path %>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title, placeholder: "title", class: "form-control" %>
  </div>
  <div class="field">
    <%= f.text_area :content, placeholder: "content...",
                              class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Create Article", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h3>Editing Article</h3>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<% provide(:title, 'Articles') %>
<p id="notice"><%= notice %></p>

<h3 style="margin: 30px 0px">Listing Articles</h3>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= editable article, :title %></td>
        <td><%= editable article, :content, type: "textarea" %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete,
                                   data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h3>New Article</h3>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<div style="margin-bottom: 30px">
<h3 style="margin: 30px 0px"> <%= editable @article, :title %> </h3>
<p>  <%= editable @article, :content, type: "wysihtml5" %> </p>

</div>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/contacts/_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@contact) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :mobile %>
      <%= f.text_field :mobile, class: 'form-control' %>

      <%= f.label :phone %>
      <%= f.text_field :phone, class: 'form-control' %>

      <%= f.label :role %>
      <%= f.select :role, Contact.roles.keys.to_a, class: 'form-control' %>

      <%= f.label :priority %>
      <%= f.select :priority, Contact.priorities.keys.to_a,
                              class: 'form-control' %>

      <%= f.label :address %>
      <%= f.text_field :address, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :note %>
      <%= f.text_area :note, class: 'form-control' %>

      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/contacts/_row.html.erb
<% contact = row %>

<td><%= editable contact, :name %></td>
<td><%= editable contact, :mobile %></td>
<td><%= editable contact, :phone %></td>
<td><%= editable contact, :role, type: :select, data: { source: roles } %></td>
<td>
  <%= editable contact, :priority, type: :select,
                                   data: { source: priorities }%>
</td>
<td><%= editable contact, :address %></td>
<td><%= editable contact, :email %></td>
<td><%= editable contact, :note, type: :textarea %></td>
<td><%= link_to 'Show', contact, class: 'btn btn-primary btn-xs' %></td>
<td>
  <%= link_to edit_contact_path(contact),
              class: 'btn btn-info btn-xs' do %>
    <i class="glyphicon glyphicon-edit"></i> Edit
  <% end %> 
</td>
<td>
  <%= link_to contact_path(contact),
              method: :delete,
              data: { confirm: 'You sure?' },
              class: 'btn btn-danger btn-xs' do %>
    <i class="glyphicon glyphicon-remove"></i> Destroy
  <% end %>     
</td>

app/views/contacts/_table_headers.html.erb
<th>Name</th>
<th>Mobile</th>
<th>Phone</th>
<th>Role</th>
<th>Priority</th>
<th>Address</th>
<th>Email</th>
<th>Note</th>
<th colspan="3"></th>

app/views/contacts/edit.html.erb
<% provide(:title, "Edit Contact") %>
<% provide(:button_text, 'Save changes') %>

<h1>Update contact</h1>
<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back to Contacts', contacts_path %>

app/views/contacts/index.html.erb
<% provide(:title, "All Contacts") %>

<h3 style="margin: 30px 0px">Listing Contacts</h3>

<% count = @contacts.offset %>
<% roles = Contact.roles.keys.to_a %>
<% priorities = Contact.priorities.keys.to_a %>

<%= will_paginate %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>No.</th>
      <%= render 'table_headers' %>
    </tr>
  </thead>
  <tbody>
    <% @contacts.each do |contact| %>
      <% count += 1 %>
      <tr>
        <td><%= count %></td>
        <%= render partial: 'row',
                   object: contact,
                   locals: { roles: roles, priorities: priorities } %>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate %>

<br/>
<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<% provide(:title, "New Contact") %>
<% provide(:button_text, 'Create contact') %>

<h1>New Contact</h1>
<%= render 'form' %>

<%= link_to 'Back to Contacts', contacts_path %>

app/views/contacts/show.html.erb
<% provide(:title, @contact.name) %>

<% roles = Contact.roles.keys.to_a %>
<% priorities = Contact.priorities.keys.to_a %>

<div class="row">
  <table class="table table-striped">
    <thead><tr><%= render 'table_headers' %></tr></thead>
    <tbody>
      <tr>
        <%= render partial: 'row',
                   object: @contact,
                   locals: { roles: roles, priorities: priorities } %>
      </tr>
    </tbody>
  </table>
</div>

<br>
<%= link_to 'Back to Contacts', contacts_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Agile Inventory Management System for Small Businesses
  </small>
  <nav>
    <ul>
      <li><%= link_to t('layouts.application.about'), about_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t('layouts.application.cute'), root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t('layouts.application.home'), root_path %></li>
        <li>
          <%= link_to t('layouts.application.contacts'), contacts_path %>
        </li>
        <li><%= link_to t('layouts.application.help'), help_path %></li>
        <li><%= link_to t('layouts.application.login'),
                        new_admin_session_path %></li>
        <li><%= link_to t('layouts.application.logout'),
                        destroy_admin_session_path,
                        method: :delete,
                        data: { confirm: 'You sure?' } %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1,
          maximum-scale=1">
    <title><%= yield(:title) %> | Cute</title>
    <meta name="description" content="Cute, an inventory management system">
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%# Gem devise needs these 2 lines %>
      <p class="notice"><%#= notice %></p>
      <p class="alert"><%#= alert %></p>      
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>    
    </div>
  </body>
</html>

app/views/material_orders/index.html.erb
<% provide(:title, "All Material Orders") %>

<h3 style="margin: 30px 0px">Listing Material Orders</h3>

<table class="table">
  <thead>
    <tr>
      <th>No.</th>
      <th>Order Title</th>
      <th>Datetime</th>
      <th>Provider</th>
      <th>Note</th>
    </tr>
  </thead>

  <tbody>

  </tbody>
</table>

<br>

<%= link_to 'New Material Order', new_material_order_path %>

app/views/material_orders/new.html.erb
<% provide(:title, 'New Material Order') %>
<h1>New Material Order</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@material_order) do |f| %>
      <%= f.label :order_title %>
      <%= f.text_field :order_title %>

      <%= f.label :provider %>
      <%= f.collection_select :contact_id, find_all_suppliers,
                              :id, :name,
                              prompt: true %>

      <%= f.label :note %>
      <%= f.text_area :note %>

      <%= f.submit "Create New Material Order", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if @contact.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@contact.errors.count, "error") %>.
    </div>
    <ul>
    <% @contact.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About Cute</h1>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Cute Help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="center jumbotron">
  <h1>Welcome to Cute</h1>
  <h2>Home page for Cute.</h2>
  <%= link_to "Sign up now!", new_admin_registration_path,
                         class: "btn btn-lg btn-primary" %>
</div>